name: BestiePanti-dev cicd build and deploy

on:
  push:
    branches: ["DEV1"]
  pull_request:
    branches: ["DEV1"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean install

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: joshuajevon/bestiepanti-images-dev
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Log in to Koyeb Container Registry
      run: echo ${{ secrets.KOYEB_API_KEY }} | docker login --username=_ --password-stdin registry.koyeb.com
    - name: Tag Docker image for Koyeb DEV
      run: docker tag joshuajevon/bestiepanti-images-dev:latest registry.koyeb.com/${{ secrets.KOYEB_APP_NAME_DEV }}/web

    - name: Push Docker image to Koyeb DEV
      run: docker push registry.koyeb.com/${{ secrets.KOYEB_APP_NAME_DEV }}/web

    - name: Deploy the app on Koyeb DEV
      run: koyeb services deploy my-service --app ${{ secrets.KOYEB_APP_NAME_DEV }}
